<?php

return [
    'income:read' => 'View income records',
    'income:write' => 'Create, update, delete income records',
    'expense:read' => 'View expense records',
    'expense:write' => 'Create, update, delete expense records',
    'debt:read' => 'View debt records',
    'debt:write' => 'Create, update, delete debt records',
    'asset:read' => 'View asset records',
    'asset:write' => 'Create, update, delete asset records',
    'budget:read' => 'View budget records',
    'budget:write' => 'Create, update, delete budget records',
    'goal:read' => 'View goal records',
    'goal:write' => 'Create, update, delete goal records',
    'income-categories:read' => 'View income categories',
    'income-categories:write' => 'Create, update, delete income categories',
    'expense-categories:read' => 'View expense categories',
    'expense-categories:write' => 'Create, update, delete expense categories',
    'zakat:read' => 'View zakat records',
    'zakat:write' => 'Create, update, delete zakat records',
    'report:read' => 'View reports',
    'report:write' => 'Create and export reports',
    'export:data' => 'Export data',
    'workspace:read' => 'View workspaces',
    'workspace:write' => 'Create and manage workspaces',
    'user:read' => 'View user profile',
    'user:write' => 'Update user profile',
    'notification:read' => 'View notifications',
    'notification:write' => 'Manage notifications',
    'transaction:read' => 'View transactions',
    'dashboard:read' => 'View dashboard KPIs',
    'subscription:read' => 'View subscription and plans',
    'subscription:write' => 'Change plan and cancel subscription',
    '*' => 'Full access — all abilities',
];
